version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'hotels'
      MYSQL_USER: 'django'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql
  frontend:
    build: ./client
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./client:/usr/src/frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
  backend:
    build: ./server
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/backend
    ports:
      - '8000:8000'
    depends_on:
      - db